version: "3.9"
services:
  db:
    image: postgres:16
    environment:
      POSTGRES_USER: sentstocks
      POSTGRES_PASSWORD: sentstocks
      POSTGRES_DB: sentstocks
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data
  adminer:
    image: adminer
    restart: always
    ports:
      - "8080:8080"
volumes:
  db_data: